<?php
    echo $this->showMessages();
?>
<div id="login">
    <h1><?php echo $this->translate("Register"); ?></h1>
    <?php
    /**
     * @var \Zend\Form\Form $form
     */
    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('user');
    $form->setAttribute('action', $this->url('register'));

    echo $this->form()->openTag($form);
    ?>
    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('username'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('username'));
        echo $this->formInput($fieldset->get('username'));
        ?>
    </div>
    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('email'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('email'));
        echo $this->formEmail($fieldset->get('email'));
        ?>
    </div>
    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('password'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('password'));
        echo $this->formPassword($fieldset->get('password'));
        ?>
    </div>
    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('repassword'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('repassword'));
        echo $this->formPassword($fieldset->get('repassword'));
        ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Register'))); ?>
    <?php echo $this->form()->closeTag() ?>
</div>